version: 0.0
os: linux
files:
  - source: /server.js
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/installnodejs.sh
      timeout: 300
      runas: root
    - location: scripts/startserver.sh
      timeout: 300
      runas: root
